common:
  img_topic: "/camera/left/image_mono"
  lid_topic: "/ouster/point_cloud"
  imu_topic: "/imu/data"
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false
  print_debug_info: false

extrin_calib:
  extrinsic_T: [0.04357876, -0.0025 , 0.10768]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  Rcl: [0.0, -1.0,  0.0, 
        0.0,  0.0, -1.0, 
        1.0,  0.0,  0.0] 
  Pcl: [0.085, -0.12218, -0.06971161]

time_offset: 
  imu_time_offset: 0.0
  img_time_offset: 0.0
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 1
  filter_size_surf: 0.2
  lidar_type: 3 # Livox Avia LiDAR   AVIA = 1,, VELO16 = 2, OUST64 = 3, L515 = 4, XT32 = 5, PANDAR128 = 6

  scan_line: 128
  blind: 0.8

vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 
  patch_size: 8
  patch_pyrimid_level: 4
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.2 # 0.2
  gyr_cov: 0.5 # 0.5
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.0025 # 0.005
  voxel_size: 0.25
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:  
  map_sliding_en: true
  half_map_size: 500
  sliding_thresh: 40

uav:
  imu_rate_odom: true
  gravity_align_en: false

publish:
  dense_map_en: false
  pub_effect_point_en: false 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "corridors_dolly"
  pose_output_en: true

pcd_save:
  pcd_save_en: false
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
